---
name: Generate Podcast Feeds
on: [push]
#permissions:
#  contents: write
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run Feed Generator
        uses: swilson42/feedproc@master
